[package]
name = "ankhimate-editor"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Ankhimate/editor"
authors = ["Ankhimate Contributors"]

[dependencies]
ankhimate-core = { version = "0.1.0", git = "https://github.com/Ankhimate/core", rev = "82d4490d08e2f56298abdf1b4692bb8593c048f9" }
ankhimate-document = { version = "0.1.0", git = "https://github.com/Ankhimate/document", rev = "9c1920909747d66ac5cb7702cf0b308ea1654f8f" }
ankhimate-formats = { version = "0.1.0", git = "https://github.com/Ankhimate/formats", rev = "97cf02ee6a4f2246c6f3ea7fe4575fca4f84b5a4" }
ankhimate-export = { version = "0.1.0", git = "https://github.com/Ankhimate/export", rev = "f7ee43c7138e5452f5bf87c0a880f58612093b93" }
ankhimate-plugins = { version = "0.1.0", git = "https://github.com/Ankhimate/plugins", rev = "48568c9dd80435a0500935b698e4c6d3b3f21f8d" }
rfd = "0.15"
eframe = "0.34.3"
env_logger = "0.11.10"
log = "0.4.32"
wgpu = "29.0.3"
egui_tiles = "0.15.0"
bytemuck = { version = "1.25", features = ["derive"] }
glam = "0.33.1"
serde_json = "1.0.150"
serde = { version = "1.0.228", features = ["derive"] }
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "webp"] }
directories = "6.0.0"
spade = "2.15.1"
resvg = { version = "0.48", default-features = false }
ureq = "2.12"

[dev-dependencies]
tempfile = "3"

[profile.dev.package."*"]
opt-level = 1
debug = false
