use std::fs;
use std::path::{Path, PathBuf};

const VERBS_PATH: &str = "docs/reference/document-verbs.md";
const MCP_PATH: &str = "docs/reference/mcp-tools.md";

fn main() {
    let command = std::env::args().nth(1).unwrap_or_default();
    let result = match command.as_str() {
        "docs-sync" => sync(),
        "docs-check" => check(),
        _ => Err("usage: cargo run -p xtask -- <docs-sync|docs-check>".into()),
    };
    if let Err(error) = result {
        eprintln!("xtask: {error}");
        std::process::exit(1);
    }
}

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

fn generated() -> [(PathBuf, String); 2] {
    [
        (root().join(VERBS_PATH), render_verbs()),
        (root().join(MCP_PATH), render_tools()),
    ]
}

fn sync() -> Result<(), String> {
    for (path, contents) in generated() {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        fs::write(&path, contents).map_err(|e| format!("{}: {e}", path.display()))?;
        println!("wrote {}", path.display());
    }
    Ok(())
}

fn check() -> Result<(), String> {
    for (path, expected) in generated() {
        let actual = fs::read_to_string(&path)
            .map_err(|e| format!("{}: {e}; run docs-sync", path.display()))?;
        if actual != expected {
            return Err(format!("{} is stale; run docs-sync", path.display()));
        }
    }
    let spec = fs::read_to_string(root().join("docs/format-spec.md")).map_err(|e| e.to_string())?;
    let version = ankhimate_formats::schema::CURRENT_VERSION;
    if !spec.contains(&format!("version {version}")) {
        return Err(format!(
            "format specification does not name schema version {version}"
        ));
    }
    check_json(&root().join("docs/examples"))?;
    check_links(&root().join("docs"))?;
    check_status_metadata()?;
    println!("documentation checks passed");
    Ok(())
}

fn render_verbs() -> String {
    let ops = ankhimate_document::DocOps::builtin();
    let mut out = generated_header("Document verb reference");
    out.push_str("These are the undoable document verbs exposed to headless callers.\n\n");
    for id in ops.ids() {
        let op = ops.get(id).unwrap();
        let mode = op
            .requires_mode()
            .map(|mode| format!("{mode:?}"))
            .unwrap_or_else(|| "Any".into());
        out.push_str(&format!(
            "## `{}`\n\n**{}** · Mode: `{}`\n\n```json\n",
            id,
            op.label(),
            mode
        ));
        out.push_str(&serde_json::to_string_pretty(&op.schema()).unwrap());
        out.push_str("\n```\n\n");
    }
    out
}

fn render_tools() -> String {
    let mut out = generated_header("MCP tool reference");
    out.push_str(
        "Tools are listed in session workflow order. Schemas are exact registry output.\n\n",
    );
    for tool in ankhimate_mcp::tools::all() {
        out.push_str(&format!(
            "## `{}`\n\n{}\n\n```json\n",
            tool.name, tool.description
        ));
        out.push_str(&serde_json::to_string_pretty(&tool.schema).unwrap());
        out.push_str("\n```\n\n");
    }
    out
}

fn generated_header(title: &str) -> String {
    format!(
        "---\ntitle: {title}\ndescription: Generated registry reference; do not edit manually.\n---\n\n# {title}\n\n> Generated by `cargo run -p xtask -- docs-sync`. Do not edit manually.\n\n"
    )
}

fn check_json(dir: &Path) -> Result<(), String> {
    for path in files(dir)? {
        if path.extension().and_then(|s| s.to_str()) == Some("json") {
            let text = fs::read_to_string(&path).map_err(|e| e.to_string())?;
            serde_json::from_str::<serde_json::Value>(&text)
                .map_err(|e| format!("invalid JSON {}: {e}", path.display()))?;
        }
    }
    Ok(())
}

fn check_links(dir: &Path) -> Result<(), String> {
    for path in files(dir)? {
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        let text = fs::read_to_string(&path).map_err(|e| e.to_string())?;
        for piece in text.split("](").skip(1) {
            let Some(target) = piece.split(')').next() else {
                continue;
            };
            let target = target.split('#').next().unwrap_or(target);
            if target.is_empty()
                || target.starts_with('/')
                || target.starts_with("http://")
                || target.starts_with("https://")
                || target.starts_with("mailto:")
            {
                continue;
            }
            if !path.parent().unwrap().join(target).exists() {
                return Err(format!("broken local link in {}: {target}", path.display()));
            }
        }
    }
    Ok(())
}

fn check_status_metadata() -> Result<(), String> {
    let status = fs::read_to_string(root().join("docs/getting-started/status.md"))
        .map_err(|e| e.to_string())?;
    for label in [
        "Current",
        "Partial",
        "Experimental",
        "Planned",
        "Not supported",
    ] {
        if !status.contains(label) {
            return Err(format!("status vocabulary is missing `{label}`"));
        }
    }
    let plan =
        fs::read_to_string(root().join("docs/DOCUMENTATION_PLAN.md")).map_err(|e| e.to_string())?;
    if !plan.contains("## Validation") || !plan.contains("## Source map") {
        return Err("DOCUMENTATION_PLAN.md lacks validation or source metadata".into());
    }
    Ok(())
}

fn files(dir: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    for entry in fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))? {
        let path = entry.map_err(|e| e.to_string())?.path();
        if path.is_dir() {
            out.extend(files(&path)?);
        } else {
            out.push(path);
        }
    }
    Ok(out)
}
